name: radditz
description: A social media app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  any_link_preview: ^3.0.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  appwrite: ^8.2.0
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.1.6
  flutter_riverpod: ^2.1.3
  fpdart: ^0.5.0
  image_picker: ^0.8.6+1
  like_button: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/svgs/
